name: Build
on:
  push:
    branches:
      - master
      - actions/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Exclude Tip Sheet PDFs from Git LFS fetch
        run: |
          git config --global lfs.fetchexclude "tip_sheets"
      - name: Install crcmod
        run: |
          sudo apt-get install gcc python3-dev python3-setuptools
          sudo pip3 uninstall crcmod
          sudo pip3 install --no-cache-dir -U crcmod
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v1
      - name: Confirm GCloud setup
        run: gcloud info
      - name: Install NPM
        run: npm install
      - name: Build website
        run: npm run build
      - name: Upload files to Google Cloud Storage (rsync)
        id: upload-files
        timeout-minutes: 15
        run: gsutil rsync -d -R -c -x "assets/tip_sheets/.*$" ./dist/static gs://covid-website-storage2 && gsutil web set -m index.html gs://covid-website-storage2/
