name: Build
on:
  push:
    branches:
      - master
      - drive-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - run: gcloud info
      - name: Download from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          download-from: Covid_Website_Assets
          download-to: ./drive_assets
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - id: upload-files
        name: Upload files to google drive (rsync)
        run: gsutil -m rsync -d -R -c ./dist/static gs://covid19p-testing1 && gsutil web set -m index.html gs://covid19p-testing1/
