name: Build
on:
  push:
    branches:
      - master
      - drive-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./drive_assets
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: rclone - Download assets from Google Drive
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy -v gdrive:Covid_Website_Assets ./drive_assets
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - run: gcloud info
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - id: upload-files
        name: Upload files to google drive (rsync)
        run: gsutil -m rsync -d -R -c ./dist/static gs://covid19p-testing1 && gsutil web set -m index.html gs://covid19p-testing1/
